#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: dapp-prb-power-triton-grpc

services:
  prb-power-triton-grpc:
    build:
      context: ../..
      dockerfile: applications/prb-power-triton-grpc/Dockerfile
    image: dapp-prb-power-triton-grpc:latest
    container_name: dapp-prb-power-triton-grpc
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all    # MIG Partition ID if enabled (e.g., MIG-xyz)
      - CUDA_VISIBLE_DEVICES=0        # MIG Partition ID if enabled (e.g., MIG-xyz)
      # MPS configuration - Uncomment these lines if using MPS instead of MIG:
      # - CUDA_DEVICE_MAX_CONNECTIONS=8
      # - CUDA_MPS_PIPE_DIRECTORY=/var
      # - CUDA_MPS_LOG_DIRECTORY=/var
    network_mode: "host"
    volumes:
      - ./logs:/logs
    privileged: true
    ipc: ${IPC_MODE:-container:nv-cubb}